name: Bookmark Summary

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
  workflow_dispatch:

concurrency:
  group: mygroup
  cancel-in-progress: false

jobs:
  summarize:
    permissions:
      contents: write  # To push a branch 
      pull-requests: write  # To create a PR from that branch
      
    runs-on: ubuntu-latest
    steps:
    - name: Checkout bookmark-collection
      uses: actions/checkout@v2
      with:
        path: bookmark-collection

    - name: Checkout bookmark-ai-summary
      uses: actions/checkout@v2
      with:
        repository: zo0043/bookmark-ai-summary
        path: bookmark-ai-summary
        token: ${{ secrets.PAT }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.lock

    - name: Process changes
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_API_MODEL: ${{ secrets.OPENAI_API_MODEL }}
        OPENAI_API_ENDPOINT: ${{ secrets.OPENAI_API_ENDPOINT }}
      run: |
        python bookmark-ai-summary/src/bookmark_ai_summary/bookmark_process_changes.py

    - name: Commit changes to bookmark-summary
      run: |
        cd bookmark-ai-summary
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add new summaries" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

